
export const ingredients = [
  'Allspice',
  'Almonds',
  'Apples',
  'Apricots',
  'Avocado',
  'Bacon',
  'Basil',
  'Bay leaves',
  'Beans',
  'Beef',
  'Bell peppers',
  'Black pepper',
  'Blueberries',
  'Broccoli',
  'Brown rice',
  'Butter',
  'Cabbage',
  'Carrots',
  'Cauliflower',
  'Cayenne pepper',
  'Celery',
  'Cheese',
  'Cherries',
  'Chicken',
  'Chocolate',
  'Cilantro',
  'Cinnamon',
  'Cloves',
  'Coconut',
  'Corn',
  'Cumin',
  'Dill',
  'Eggs',
  'Fennel',
  'Fish',
  'Garlic',
  'Ginger',
  'Grapes',
  'Green beans',
  'Honey',
  'Jalapeño',
  'Kale',
  'Lemon',
  'Lentils',
  'Lettuce',
  'Lime',
  'Maple syrup',
  'Milk',
  'Mushrooms',
  'Mustard',
  'Nutmeg',
  'Oats',
  'Olive oil',
  'Onions',
  'Orange',
  'Oregano',
  'Paprika',
  'Parmesan cheese',
  'Parsley',
  'Peaches',
  'Peanut butter',
  'Peanuts',
  'Pears',
  'Peas',
  'Pecans',
  'Pineapple',
  'Pistachios',
  'Pork',
  'Potatoes',
  'Quinoa',
  'Raisins',
  'Red pepper flakes',
  'Rosemary',
  'Saffron',
  'Sage',
  'Salmon',
  'Salt',
  'Scallions',
  'Sesame oil',
  'Sesame seeds',
  'Shrimp',
  'Spinach',
  'Strawberries',
  'Sugar',
  'Sunflower seeds',
  'Sweet potatoes',
  'Tarragon',
  'Thyme',
  'Tomatoes',
  'Turkey',
  'Vanilla extract',
  'Vinegar',
  'Walnuts',
  'Watermelon',
  'White pepper',
  'White wine',
  'Worcestershire sauce',
  'Yogurt',
  'Zucchini',
  'Soy sauce'
];

export const recipes = [
  { recipeName: 'Chicken Alfredo Pasta', ingredients: ['Chicken', 'Fettuccine pasta', 'Heavy cream', 'Parmesan cheese', 'Garlic', 'Butter', 'Salt', 'Pepper'], cookTime: '30 minutes' },
  { recipeName: 'Vegetable Lasagna', ingredients: ['Lasagna noodles', 'Tomato sauce', 'Ricotta cheese', 'Mozzarella cheese', 'Spinach', 'Zucchini', 'Onions', 'Garlic'], cookTime: '1 hour' },
  { recipeName: 'Teriyaki Salmon', ingredients: ['Salmon', 'Teriyaki sauce', 'Soy sauce', 'Brown sugar', 'Ginger', 'Garlic', 'Green onions', 'Rice'], cookTime: '25 minutes' },
  { recipeName: 'Cesar Wrap', ingredients: ['Grilled chicken', 'Lettuce', 'Parmesan cheese', 'Caesar dressing', 'Tomatoes', 'Flour tortilla'], cookTime: '15 minutes' },
  { recipeName: 'Pumpkin Soup', ingredients: ['Pumpkin puree', 'Chicken broth', 'Onions', 'Garlic', 'Thyme', 'Heavy cream', 'Nutmeg'], cookTime: '40 minutes' },
  { recipeName: 'Beef Tacos', ingredients: ['Ground beef', 'Taco seasoning', 'Tortillas', 'Lettuce', 'Tomatoes', 'Cheese', 'Sour cream'], cookTime: '20 minutes' },
  { recipeName: 'Salmon Avocado Salad', ingredients: ['Salmon', 'Avocado', 'Mixed greens', 'Cherry tomatoes', 'Cucumber', 'Lemon vinaigrette'], cookTime: '15 minutes' },
  { recipeName: 'Penne alla Vodka', ingredients: ['Penne pasta', 'Vodka sauce', 'Heavy cream', 'Parmesan cheese', 'Basil', 'Garlic'], cookTime: '25 minutes' },
  { recipeName: 'Mushroom Risotto', ingredients: ['Arborio rice', 'Mushrooms', 'Chicken broth', 'White wine', 'Parmesan cheese', 'Onions', 'Garlic'], cookTime: '35 minutes' },
  { recipeName: 'Honey Mustard Chicken', ingredients: ['Chicken breasts', 'Honey', 'Dijon mustard', 'Garlic', 'Thyme', 'Olive oil', 'Salt', 'Pepper'], cookTime: '30 minutes' },
  { recipeName: 'Avocado Toast', ingredients: ['Bread', 'Avocado', 'Cherry tomatoes', 'Red pepper flakes', 'Lemon', 'Salt', 'Pepper'], cookTime: '10 minutes' },
  { recipeName: 'Shrimp and Broccoli Stir-Fry', ingredients: ['Shrimp', 'Broccoli', 'Soy sauce', 'Ginger', 'Garlic', 'Sesame oil', 'Rice'], cookTime: '20 minutes' },
  { recipeName: 'Ratatouille', ingredients: ['Eggplant', 'Zucchini', 'Bell peppers', 'Tomatoes', 'Onions', 'Garlic', 'Herbs de Provence'], cookTime: '45 minutes' },
  { recipeName: 'Chickpea Curry', ingredients: ['Chickpeas', 'Tomatoes', 'Coconut milk', 'Onions', 'Garlic', 'Curry powder', 'Spinach'], cookTime: '30 minutes' },
  { recipeName: 'Lemon Garlic Roast Chicken', ingredients: ['Whole chicken', 'Lemon', 'Garlic', 'Thyme', 'Rosemary', 'Olive oil', 'Salt', 'Pepper'], cookTime: '1 hour 15 minutes' },
  { recipeName: 'Sweet Potato Fries', ingredients: ['Sweet potatoes', 'Olive oil', 'Paprika', 'Garlic powder', 'Salt', 'Pepper'], cookTime: '25 minutes' },
  { recipeName: 'Eggplant Parmesan', ingredients: ['Eggplant', 'Tomato sauce', 'Mozzarella cheese', 'Parmesan cheese', 'Breadcrumbs', 'Eggs'], cookTime: '40 minutes' },
  { recipeName: 'Black Bean Quesadillas', ingredients: ['Black beans', 'Tortillas', 'Cheese', 'Onions', 'Cilantro', 'Sour cream'], cookTime: '20 minutes' },
  { recipeName: 'Cauliflower Fried Rice', ingredients: ['Cauliflower rice', 'Shrimp', 'Peas', 'Carrots', 'Soy sauce', 'Eggs', 'Green onions'], cookTime: '30 minutes' },
  { recipeName: 'Peach Cobbler', ingredients: ['Peaches', 'Flour', 'Sugar', 'Butter', 'Cinnamon', 'Baking powder', 'Milk'], cookTime: '45 minutes' },
  { recipeName: 'Vegetable Fajitas', ingredients: ['Bell peppers', 'Onions', 'Zucchini', 'Mushrooms', 'Soy sauce', 'Fajita seasoning', 'Tortillas'], cookTime: '25 minutes' },
  { recipeName: 'Lemon Blueberry Muffins', ingredients: ['Flour', 'Blueberries', 'Sugar', 'Butter', 'Eggs', 'Lemon zest', 'Baking powder'], cookTime: '20 minutes' },
  { recipeName: 'Sushi Rolls', ingredients: ['Sushi rice', 'Nori sheets', 'Fish (tuna, salmon)', 'Avocado', 'Cucumber', 'Soy sauce', 'Wasabi', 'Pickled ginger'], cookTime: '40 minutes' },
  { recipeName: 'Butternut Squash Soup', ingredients: ['Butternut squash', 'Onions', 'Carrots', 'Vegetable broth', 'Coconut milk', 'Cinnamon', 'Nutmeg'], cookTime: '35 minutes' },
  { recipeName: 'Chicken Enchiladas', ingredients: ['Shredded chicken', 'Enchilada sauce', 'Cheese', 'Tortillas', 'Lettuce', 'Tomatoes', 'Sour cream'], cookTime: '30 minutes' },
  { recipeName: 'Peach Salsa', ingredients: ['Peaches', 'Tomatoes', 'Red onion', 'Cilantro', 'Lime', 'Salt', 'Pepper'], cookTime: '15 minutes' },
  { recipeName: 'Baked Ziti', ingredients: ['Ziti pasta', 'Tomato sauce', 'Ricotta cheese', 'Mozzarella cheese', 'Parmesan cheese', 'Basil'], cookTime: '35 minutes' },
  { recipeName: 'Honey Soy Glazed Salmon', ingredients: ['Salmon', 'Soy sauce', 'Honey', 'Garlic', 'Ginger', 'Green onions', 'Sesame seeds'], cookTime: '20 minutes' },
  { recipeName: 'Mango Coconut Smoothie', ingredients: ['Mango', 'Coconut milk', 'Yogurt', 'Honey', 'Ice'], cookTime: '10 minutes' },
  { recipeName: 'Crispy Baked Chicken Wings', ingredients: ['Chicken wings', 'Baking powder', 'Salt', 'Pepper', 'BBQ sauce', 'Blue cheese dressing'], cookTime: '50 minutes' },
  { recipeName: 'Pesto Chicken Panini', ingredients: ['Chicken breasts', 'Pesto sauce', 'Mozzarella cheese', 'Tomato', 'Ciabatta bread', 'Butter'], cookTime: '25 minutes' },
  { recipeName: 'Bruschetta', ingredients: ['Tomatoes', 'Basil', 'Garlic', 'Balsamic vinegar', 'Olive oil', 'Baguette', 'Parmesan cheese'], cookTime: '15 minutes' },
  { recipeName: 'Mediterranean Quinoa Salad', ingredients: ['Quinoa', 'Cucumber', 'Tomatoes', 'Kalamata olives', 'Feta cheese', 'Red onion', 'Olive oil'], cookTime: '20 minutes' },
  { recipeName: 'Beef and Broccoli Stir-Fry', ingredients: ['Beef', 'Broccoli', 'Soy sauce', 'Ginger', 'Garlic', 'Sesame oil', 'Rice'], cookTime: '25 minutes' },
  { recipeName: 'Chocolate Banana Bread', ingredients: ['Bananas', 'Flour', 'Sugar', 'Cocoa powder', 'Eggs', 'Chocolate chips', 'Baking soda'], cookTime: '50 minutes' },
  { recipeName: 'Cucumber Gazpacho', ingredients: ['Cucumbers', 'Tomatoes', 'Bell pepper', 'Red onion', 'Garlic', 'Vinegar', 'Olive oil'], cookTime: '15 minutes' },
  { recipeName: 'Peanut Butter Energy Bites', ingredients: ['Oats', 'Peanut butter', 'Honey', 'Chia seeds', 'Flaxseeds', 'Vanilla extract'], cookTime: '10 minutes' },
  { recipeName: 'Vegetarian Pad Thai', ingredients: ['Rice noodles', 'Tofu', 'Bean sprouts', 'Carrots', 'Peanuts', 'Soy sauce', 'Lime'], cookTime: '30 minutes' },
  { recipeName: 'Classic Margherita Pizza', ingredients: ['Pizza dough', 'Tomato sauce', 'Mozzarella cheese', 'Tomatoes', 'Basil', 'Olive oil'], cookTime: '20 minutes' },
  { recipeName: 'Caramel Apple Crisp', ingredients: ['Apples', 'Caramel sauce', 'Flour', 'Oats', 'Brown sugar', 'Cinnamon', 'Butter'], cookTime: '40 minutes' },
  { recipeName: 'Lemon Raspberry Cheesecake', ingredients: ['Graham cracker crust', 'Cream cheese', 'Sugar', 'Eggs', 'Lemon juice', 'Raspberry sauce'], cookTime: '1 hour' },
  { recipeName: 'Stuffed Bell Peppers', ingredients: ['Bell peppers', 'Ground beef', 'Rice', 'Tomato sauce', 'Cheese', 'Onions', 'Garlic'], cookTime: '35 minutes' },
  { recipeName: 'Cajun Shrimp Pasta', ingredients: ['Shrimp', 'Pasta', 'Tomatoes', 'Cream', 'Cajun seasoning', 'Garlic', 'Parmesan cheese'], cookTime: '25 minutes' },
  { recipeName: 'Mushroom and Spinach Quesadillas', ingredients: ['Mushrooms', 'Spinach', 'Tortillas', 'Cheese', 'Onions', 'Sour cream'], cookTime: '20 minutes' },
  { recipeName: 'Lentil Soup', ingredients: ['Lentils', 'Carrots', 'Celery', 'Onions', 'Garlic', 'Vegetable broth', 'Tomato paste'], cookTime: '40 minutes' },
  { recipeName: 'Orange Glazed Chicken', ingredients: ['Chicken thighs', 'Orange marmalade', 'Soy sauce', 'Garlic', 'Ginger', 'Green onions', 'Sesame seeds'], cookTime: '30 minutes' },
  { recipeName: 'Pumpkin Pancakes', ingredients: ['Pumpkin puree', 'Flour', 'Milk', 'Eggs', 'Sugar', 'Baking powder', 'Cinnamon'], cookTime: '20 minutes' },
  { recipeName: 'Creamy Garlic Mashed Potatoes', ingredients: ['Potatoes', 'Butter', 'Cream', 'Garlic', 'Salt', 'Pepper'], cookTime: '30 minutes' },
  { recipeName: 'Berry Parfait', ingredients: ['Mixed berries', 'Yogurt', 'Granola', 'Honey'], cookTime: '15 minutes' },
  { recipeName: 'Italian Wedding Soup', ingredients: ['Meatballs', 'Orzo pasta', 'Spinach', 'Carrots', 'Onions', 'Chicken broth'], cookTime: '35 minutes' },
  { recipeName: 'Chicken Piccata', ingredients: ['Chicken breasts', 'Flour', 'Lemon', 'Capers', 'Chicken broth', 'Butter', 'Parsley'], cookTime: '30 minutes' },
  { recipeName: 'Ginger Turmeric Tea', ingredients: ['Ginger', 'Turmeric', 'Honey', 'Lemon', 'Water'], cookTime: '10 minutes' },
  { recipeName: 'Sweet and Sour Tofu', ingredients: ['Tofu', 'Bell peppers', 'Pineapple', 'Soy sauce', 'Vinegar', 'Ketchup', 'Brown sugar'], cookTime: '25 minutes' },
  { recipeName: 'Cherry Tomato Bruschetta', ingredients: ['Cherry tomatoes', 'Basil', 'Garlic', 'Balsamic glaze', 'Baguette', 'Olive oil'], cookTime: '15 minutes' },
];



export const combos = [
  { combinationId: 1, ingredients: ['Tomatoes', 'Mozzarella', 'Basil', 'Olive oil', 'Balsamic vinegar'] },
  { combinationId: 2, ingredients: ['Chicken', 'Lemon', 'Garlic', 'Thyme', 'Olive oil'] },
  { combinationId: 3, ingredients: ['Salmon', 'Dill', 'Lemon', 'Garlic', 'Olive oil'] },
  { combinationId: 4, ingredients: ['Avocado', 'Tomatoes', 'Red onion', 'Cilantro', 'Lime'] },
  { combinationId: 5, ingredients: ['Strawberries', 'Spinach', 'Feta cheese', 'Balsamic vinaigrette', 'Walnuts'] },
  { combinationId: 6, ingredients: ['Quinoa', 'Broccoli', 'Cherry tomatoes', 'Feta cheese', 'Olive oil'] },
  { combinationId: 7, ingredients: ['Pasta', 'Basil', 'Garlic', 'Tomatoes', 'Parmesan cheese'] },
  { combinationId: 8, ingredients: ['Blueberries', 'Greek yogurt', 'Honey', 'Almonds', 'Granola'] },
  { combinationId: 9, ingredients: ['Shrimp', 'Garlic', 'Lemon', 'Butter', 'Parsley'] },
  { combinationId: 10, ingredients: ['Cucumber', 'Tomatoes', 'Red onion', 'Feta cheese', 'Olives'] }
];
