
export const ingredients = [
  'Allspice',
  'Almonds',
  'Apples',
  'Apricots',
  'Avocado',
  'Bacon',
  'Basil',
  'Bay leaves',
  'Beans',
  'Beef',
  'Bell peppers',
  'Black pepper',
  'Blueberries',
  'Broccoli',
  'Brown rice',
  'Butter',
  'Cabbage',
  'Carrots',
  'Cauliflower',
  'Cayenne pepper',
  'Celery',
  'Cheese',
  'Cherries',
  'Chicken',
  'Chocolate',
  'Cilantro',
  'Cinnamon',
  'Cloves',
  'Coconut',
  'Corn',
  'Cumin',
  'Dill',
  'Eggs',
  'Fennel',
  'Fish',
  'Garlic',
  'Ginger',
  'Grapes',
  'Green beans',
  'Honey',
  'Jalapeño',
  'Kale',
  'Lemon',
  'Lentils',
  'Lettuce',
  'Lime',
  'Maple syrup',
  'Milk',
  'Mushrooms',
  'Mustard',
  'Nutmeg',
  'Oats',
  'Olive oil',
  'Onions',
  'Orange',
  'Oregano',
  'Paprika',
  'Parmesan cheese',
  'Parsley',
  'Peaches',
  'Peanut butter',
  'Peanuts',
  'Pears',
  'Peas',
  'Pecans',
  'Pineapple',
  'Pistachios',
  'Pork',
  'Potatoes',
  'Quinoa',
  'Raisins',
  'Red pepper flakes',
  'Rosemary',
  'Saffron',
  'Sage',
  'Salmon',
  'Salt',
  'Scallions',
  'Sesame oil',
  'Sesame seeds',
  'Shrimp',
  'Spinach',
  'Strawberries',
  'Sugar',
  'Sunflower seeds',
  'Sweet potatoes',
  'Tarragon',
  'Thyme',
  'Tomatoes',
  'Turkey',
  'Vanilla extract',
  'Vinegar',
  'Walnuts',
  'Watermelon',
  'White pepper',
  'White wine',
  'Worcestershire sauce',
  'Yogurt',
  'Zucchini',
  'Soy sauce'
];

export const recipes = [
  { recipeName: 'Spaghetti Bolognese', ingredients: ['Beef', 'Tomatoes', 'Onions', 'Garlic', 'Oregano', 'Basil', 'Olive oil', 'Spaghetti'] },
  { recipeName: 'Chicken Stir-Fry', ingredients: ['Chicken', 'Broccoli', 'Carrots', 'Soy sauce', 'Ginger', 'Garlic', 'Bell peppers', 'Rice'] },
  { recipeName: 'Caprese Salad', ingredients: ['Tomatoes', 'Mozzarella', 'Basil', 'Balsamic vinegar', 'Olive oil', 'Salt', 'Pepper'] },
  { recipeName: 'Vegetarian Chili', ingredients: ['Beans', 'Tomatoes', 'Onions', 'Garlic', 'Cumin', 'Chili powder', 'Bell peppers'] },
  { recipeName: 'Pesto Pasta', ingredients: ['Pasta', 'Basil', 'Garlic', 'Parmesan cheese', 'Pine nuts', 'Olive oil'] },
  { recipeName: 'Grilled Salmon', ingredients: ['Salmon', 'Lemon', 'Dill', 'Olive oil', 'Salt', 'Pepper'] },
  { recipeName: 'Caesar Salad', ingredients: ['Lettuce', 'Chicken', 'Parmesan cheese', 'Croutons', 'Caesar dressing'] },
  { recipeName: 'Mango Salsa Chicken', ingredients: ['Chicken', 'Mango', 'Tomatoes', 'Onions', 'Cilantro', 'Lime', 'Salt'] },
  { recipeName: 'Quinoa and Vegetable Stir-Fry', ingredients: ['Quinoa', 'Broccoli', 'Carrots', 'Soy sauce', 'Garlic', 'Ginger'] },
  { recipeName: 'Blueberry Pancakes', ingredients: ['Flour', 'Blueberries', 'Milk', 'Eggs', 'Sugar', 'Baking powder', 'Butter'] },
  { recipeName: 'Greek Salad', ingredients: ['Cucumber', 'Tomatoes', 'Olives', 'Feta cheese', 'Red onion', 'Olive oil', 'Oregano'] },
  { recipeName: 'BBQ Chicken Pizza', ingredients: ['Chicken', 'BBQ sauce', 'Mozzarella', 'Red onion', 'Cilantro', 'Pizza dough'] },
  { recipeName: 'Garlic Shrimp Pasta', ingredients: ['Shrimp', 'Pasta', 'Garlic', 'Cherry tomatoes', 'Parsley', 'Lemon', 'Olive oil'] },
  { recipeName: 'Egg Salad Sandwich', ingredients: ['Eggs', 'Mayonnaise', 'Mustard', 'Bread', 'Lettuce', 'Tomatoes'] },
  { recipeName: 'Chocolate Chip Cookies', ingredients: ['Flour', 'Sugar', 'Butter', 'Chocolate chips', 'Eggs', 'Vanilla extract'] },
  { recipeName: 'Vegetable Curry', ingredients: ['Potatoes', 'Carrots', 'Peas', 'Coconut milk', 'Curry powder', 'Garlic', 'Ginger'] },
  { recipeName: 'Fruit Smoothie', ingredients: ['Banana', 'Berries', 'Yogurt', 'Honey', 'Milk', 'Ice'] },
  { recipeName: 'Spinach and Feta Stuffed Chicken', ingredients: ['Chicken', 'Spinach', 'Feta cheese', 'Garlic', 'Olive oil', 'Salt', 'Pepper'] },
  { recipeName: 'Tomato Basil Soup', ingredients: ['Tomatoes', 'Onions', 'Garlic', 'Basil', 'Chicken broth', 'Cream', 'Olive oil'] },
  { recipeName: 'Tuna Salad Wrap', ingredients: ['Tuna', 'Mayonnaise', 'Celery', 'Lettuce', 'Tomatoes', 'Tortilla'] }
];

export const combos = [
  { combinationId: 1, ingredients: ['Tomatoes', 'Mozzarella', 'Basil', 'Olive oil', 'Balsamic vinegar'] },
  { combinationId: 2, ingredients: ['Chicken', 'Lemon', 'Garlic', 'Thyme', 'Olive oil'] },
  { combinationId: 3, ingredients: ['Salmon', 'Dill', 'Lemon', 'Garlic', 'Olive oil'] },
  { combinationId: 4, ingredients: ['Avocado', 'Tomatoes', 'Red onion', 'Cilantro', 'Lime'] },
  { combinationId: 5, ingredients: ['Strawberries', 'Spinach', 'Feta cheese', 'Balsamic vinaigrette', 'Walnuts'] },
  { combinationId: 6, ingredients: ['Quinoa', 'Broccoli', 'Cherry tomatoes', 'Feta cheese', 'Olive oil'] },
  { combinationId: 7, ingredients: ['Pasta', 'Basil', 'Garlic', 'Tomatoes', 'Parmesan cheese'] },
  { combinationId: 8, ingredients: ['Blueberries', 'Greek yogurt', 'Honey', 'Almonds', 'Granola'] },
  { combinationId: 9, ingredients: ['Shrimp', 'Garlic', 'Lemon', 'Butter', 'Parsley'] },
  { combinationId: 10, ingredients: ['Cucumber', 'Tomatoes', 'Red onion', 'Feta cheese', 'Olives'] }
];
