
export const ingredients = [
  'Allspice',
  'Almonds',
  'Apples',
  'Apricots',
  'Avocado',
  'Bacon',
  'Basil',
  'Bay leaves',
  'Beans',
  'Beef',
  'Bell peppers',
  'Black pepper',
  'Blueberries',
  'Broccoli',
  'Brown rice',
  'Butter',
  'Cabbage',
  'Carrots',
  'Cauliflower',
  'Cayenne pepper',
  'Celery',
  'Cheese',
  'Cherries',
  'Chicken',
  'Chocolate',
  'Cilantro',
  'Cinnamon',
  'Cloves',
  'Coconut',
  'Corn',
  'Cumin',
  'Dill',
  'Eggs',
  'Fennel',
  'Fish',
  'Garlic',
  'Ginger',
  'Grapes',
  'Green beans',
  'Honey',
  'Jalapeño',
  'Kale',
  'Lemon',
  'Lentils',
  'Lettuce',
  'Lime',
  'Maple syrup',
  'Milk',
  'Mushrooms',
  'Mustard',
  'Nutmeg',
  'Oats',
  'Olive oil',
  'Onions',
  'Orange',
  'Oregano',
  'Paprika',
  'Parmesan cheese',
  'Parsley',
  'Peaches',
  'Peanut butter',
  'Peanuts',
  'Pears',
  'Peas',
  'Pecans',
  'Pineapple',
  'Pistachios',
  'Pork',
  'Potatoes',
  'Quinoa',
  'Raisins',
  'Red pepper flakes',
  'Rosemary',
  'Saffron',
  'Sage',
  'Salmon',
  'Salt',
  'Scallions',
  'Sesame oil',
  'Sesame seeds',
  'Shrimp',
  'Spinach',
  'Strawberries',
  'Sugar',
  'Sunflower seeds',
  'Sweet potatoes',
  'Tarragon',
  'Thyme',
  'Tomatoes',
  'Turkey',
  'Vanilla extract',
  'Vinegar',
  'Walnuts',
  'Watermelon',
  'White pepper',
  'White wine',
  'Worcestershire sauce',
  'Yogurt',
  'Zucchini',
  'Soy sauce'
];

export const recipes = [
  { recipeName: 'Spaghetti Bolognese', ingredients: ['Beef', 'Tomatoes', 'Onions', 'Garlic', 'Oregano', 'Basil', 'Olive oil', 'Spaghetti'] },
  { recipeName: 'Chicken Stir-Fry', ingredients: ['Chicken', 'Broccoli', 'Carrots', 'Soy sauce', 'Ginger', 'Garlic', 'Bell peppers', 'Rice'] },
  { recipeName: 'Caprese Salad', ingredients: ['Tomatoes', 'Mozzarella', 'Basil', 'Balsamic vinegar', 'Olive oil', 'Salt', 'Pepper'] },
  { recipeName: 'Vegetarian Chili', ingredients: ['Beans', 'Tomatoes', 'Onions', 'Garlic', 'Cumin', 'Chili powder', 'Bell peppers'] },
  { recipeName: 'Pesto Pasta', ingredients: ['Pasta', 'Basil', 'Garlic', 'Parmesan cheese', 'Pine nuts', 'Olive oil'] },
  { recipeName: 'Grilled Salmon', ingredients: ['Salmon', 'Lemon', 'Dill', 'Olive oil', 'Salt', 'Pepper'] },
  { recipeName: 'Caesar Salad', ingredients: ['Lettuce', 'Chicken', 'Parmesan cheese', 'Croutons', 'Caesar dressing'] },
  { recipeName: 'Mango Salsa Chicken', ingredients: ['Chicken', 'Mango', 'Tomatoes', 'Onions', 'Cilantro', 'Lime', 'Salt'] },
  { recipeName: 'Quinoa and Vegetable Stir-Fry', ingredients: ['Quinoa', 'Broccoli', 'Carrots', 'Soy sauce', 'Garlic', 'Ginger'] },
  { recipeName: 'Blueberry Pancakes', ingredients: ['Flour', 'Blueberries', 'Milk', 'Eggs', 'Sugar', 'Baking powder', 'Butter'] },
  { recipeName: 'Greek Salad', ingredients: ['Cucumber', 'Tomatoes', 'Olives', 'Feta cheese', 'Red onion', 'Olive oil', 'Oregano'] },
  { recipeName: 'BBQ Chicken Pizza', ingredients: ['Chicken', 'BBQ sauce', 'Mozzarella', 'Red onion', 'Cilantro', 'Pizza dough'] },
  { recipeName: 'Garlic Shrimp Pasta', ingredients: ['Shrimp', 'Pasta', 'Garlic', 'Cherry tomatoes', 'Parsley', 'Lemon', 'Olive oil'] },
  { recipeName: 'Egg Salad Sandwich', ingredients: ['Eggs', 'Mayonnaise', 'Mustard', 'Bread', 'Lettuce', 'Tomatoes'] },
  { recipeName: 'Chocolate Chip Cookies', ingredients: ['Flour', 'Sugar', 'Butter', 'Chocolate chips', 'Eggs', 'Vanilla extract'] },
  { recipeName: 'Vegetable Curry', ingredients: ['Potatoes', 'Carrots', 'Peas', 'Coconut milk', 'Curry powder', 'Garlic', 'Ginger'] },
  { recipeName: 'Fruit Smoothie', ingredients: ['Banana', 'Berries', 'Yogurt', 'Honey', 'Milk', 'Ice'] },
  { recipeName: 'Spinach and Feta Stuffed Chicken', ingredients: ['Chicken', 'Spinach', 'Feta cheese', 'Garlic', 'Olive oil', 'Salt', 'Pepper'] },
  { recipeName: 'Tomato Basil Soup', ingredients: ['Tomatoes', 'Onions', 'Garlic', 'Basil', 'Chicken broth', 'Cream', 'Olive oil'] },
  { recipeName: 'Tuna Salad Wrap', ingredients: ['Tuna', 'Mayonnaise', 'Celery', 'Lettuce', 'Tomatoes', 'Tortilla'] }
];

// YYYY-MM-DDTHH:mm:ss.sssZ
// YYYY: Four-digit year
// MM: Two-digit month (01 for January, 02 for February, and so on)
// DD: Two-digit day of the month
// T: Separator indicating the start of the time portion
// HH: Two-digit hour (00 through 23)
// mm: Two-digit minute (00 through 59)
// ss: Two-digit second (00 through 59)
// sss: Three-digit milliseconds
// Z: Indicates the time is in UTC (Coordinated Universal Time)
// ex: 2024-01-27T15:30:45.000Z


export const newRecipes = [
  {
    recipeId: 1,
    recipeCreator: 101,
    dateCreated: '2021-12-12',
    recipeName: "Spaghetti Bolognese",
    recipeLikes: 0,
    recipeSaves: 0,
    recipeCooked: 0,
    recipeCategory: "Pasta",
    recipeIngredients: [
      { ingredientName: "Spaghetti", ingredientQuantity: "200g" },
      { ingredientName: "Ground Beef", ingredientQuantity: "500g" },
    ],
    recipeInstructions: "Cook spaghetti, brown ground beef, mix together, and serve!",
    recipeImage: ""
  },
  {
    recipeId: 2,
    recipeCreator: 102,
    dateCreated: '2021-08-12',
    recipeName: "Chicken Caesar Salad",
    recipeLikes: 0,
    recipeSaves: 0,
    recipeCooked: 0,
    recipeCategory: "Salad",
    recipeIngredients: [
      { ingredientName: "Chicken Breast", ingredientQuantity: "300g" },
      { ingredientName: "Romaine Lettuce", ingredientQuantity: "1 head" },
    ],
    recipeInstructions: "Grill chicken, chop lettuce, mix with Caesar dressing, and enjoy!",
    recipeImage: ""
  },
  {
    recipeId: 3,
    recipeCreator: 103,
    dateCreated: '2021-04-25',
    recipeName: "Vegetarian Pizza",
    recipeLikes: 0,
    recipeSaves: 0,
    recipeCooked: 0,
    recipeCategory: "Pizza",
    recipeIngredients: [
      { ingredientName: "Pizza Dough", ingredientQuantity: "1 ball" },
      { ingredientName: "Tomatoes", ingredientQuantity: "4 medium" },
    ],
    recipeInstructions: "Roll out dough, add toppings, bake until crust is golden brown.",
    recipeImage: ""
  },
  {
    recipeId: 4,
    recipeCreator: 104,
    dateCreated: '2021-10-12',
    recipeName: "Chocolate Chip Cookies",
    recipeLikes: 0,
    recipeSaves: 0,
    recipeCooked: 0,
    recipeCategory: "Dessert",
    recipeIngredients: [
      { ingredientName: "All-Purpose Flour", ingredientQuantity: "2 cups" },
      { ingredientName: "Chocolate Chips", ingredientQuantity: "1 cup" },
    ],
    recipeInstructions: "Mix ingredients, form cookies, bake at 350°F for 10-12 minutes.",
    recipeImage: ""
  },
  {
    recipeId: 5,
    recipeCreator: 105,
    dateCreated: '2021-02-12',
    recipeName: "Vegetable Stir Fry",
    recipeLikes: 0,
    recipeSaves: 0,
    recipeCooked: 0,
    recipeCategory: "Stir Fry",
    recipeIngredients: [
      { ingredientName: "Broccoli", ingredientQuantity: "1 cup" },
      { ingredientName: "Bell Peppers", ingredientQuantity: "2 cups" },
    ],
    recipeInstructions: "Stir-fry vegetables in a wok with your favorite sauce until tender.",
    recipeImage: ""
  },
];


export const combos = [
  { combinationId: 1, ingredients: ['Tomatoes', 'Mozzarella', 'Basil', 'Olive oil', 'Balsamic vinegar'] },
  { combinationId: 2, ingredients: ['Chicken', 'Lemon', 'Garlic', 'Thyme', 'Olive oil'] },
  { combinationId: 3, ingredients: ['Salmon', 'Dill', 'Lemon', 'Garlic', 'Olive oil'] },
  { combinationId: 4, ingredients: ['Avocado', 'Tomatoes', 'Red onion', 'Cilantro', 'Lime'] },
  { combinationId: 5, ingredients: ['Strawberries', 'Spinach', 'Feta cheese', 'Balsamic vinaigrette', 'Walnuts'] },
  { combinationId: 6, ingredients: ['Quinoa', 'Broccoli', 'Cherry tomatoes', 'Feta cheese', 'Olive oil'] },
  { combinationId: 7, ingredients: ['Pasta', 'Basil', 'Garlic', 'Tomatoes', 'Parmesan cheese'] },
  { combinationId: 8, ingredients: ['Blueberries', 'Greek yogurt', 'Honey', 'Almonds', 'Granola'] },
  { combinationId: 9, ingredients: ['Shrimp', 'Garlic', 'Lemon', 'Butter', 'Parsley'] },
  { combinationId: 10, ingredients: ['Cucumber', 'Tomatoes', 'Red onion', 'Feta cheese', 'Olives'] }
];
